services:

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL:-http://localhost:8000}
    depends_on:
      backend:
        condition: service_healthy
    restart: "always"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    build:
        context: ./backend
        dockerfile: Dockerfile
    env_file:
      - ./.env
    command: server
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - '' # Пока пусто, но будет S3
    environment:
      - SERVICE_DEBUG=1
      - PG__HOST=${POSTGRES_HOST}
      - PG__PORT=${POSTGRES_PORT}
      - PG__USER=${POSTGRES_USER}
      - PG__PASSWORD=${POSTGRES_PASSWORD}
      - PG__DB=${POSTGRES_DB}
      - AUTH__SECRET=${AUTH__SECRET}
      - AUTH__ALGORITHM=${AUTH__ALGORITHM}
      - AUTH__EXP_HOURS=${AUTH__EXP_HOURS}
      - CORS__ALLOW_ORIGINS=${CORS__ALLOW_ORIGINS:-["http://localhost:3000"]}
    stdin_open: true
    tty: true
    restart: "always"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

  postgres:
    container_name: postgres
    image: postgres:17.6-bookworm
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: "always"


  nginx:
    container_name: nginx
    image: nginx:1.29.1-bookworms
    environment:
      NGINX_PORT: ${NGINX_PORT}
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/configs:/etc/nginx/conf.d:ro
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: "always"

volumes:
  pg_data_volume:
